import {
  Utensils,
  Car,
  Home,
  Zap,
  Gamepad2,
  ShoppingBag,
  HeartPulse,
  GraduationCap,
  User,
  Gift,
  Plane,
  Circle,
  Coffee,
  Shirt,
  Smartphone,
  Music,
  Book,
  Film,
  Dumbbell,
  Baby,
  Dog,
  Cat,
  Scissors,
  Palette,
  Camera,
  Briefcase,
  Building2,
  Bus,
  Train,
  Bike,
  Fuel,
  ParkingCircle,
  Stethoscope,
  Pill,
  Apple,
  Salad,
  Wine,
  Beer,
  CupSoda,
  Pizza,
  IceCreamCone,
  Cake,
  Popcorn,
  Cigarette,
  Wifi,
  Globe,
  Phone,
  Tv,
  Monitor,
  Printer,
  Wrench,
  Hammer,
  Lightbulb,
  Droplets,
  Flame,
  Snowflake,
  Umbrella,
  CloudRain,
  TreePine,
  Flower2,
  type LucideProps,
} from 'lucide-react'
import type { ComponentType } from 'react'

/**
 * Curated set of Lucide icons for category selection.
 * Key is the stored icon name string; value is the component.
 */
export const ICON_MAP: Record<string, ComponentType<LucideProps>> = {
  utensils: Utensils,
  car: Car,
  home: Home,
  zap: Zap,
  'gamepad-2': Gamepad2,
  'shopping-bag': ShoppingBag,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  user: User,
  gift: Gift,
  plane: Plane,
  circle: Circle,
  coffee: Coffee,
  shirt: Shirt,
  smartphone: Smartphone,
  music: Music,
  book: Book,
  film: Film,
  dumbbell: Dumbbell,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  scissors: Scissors,
  palette: Palette,
  camera: Camera,
  briefcase: Briefcase,
  'building-2': Building2,
  bus: Bus,
  train: Train,
  bike: Bike,
  fuel: Fuel,
  'parking-circle': ParkingCircle,
  stethoscope: Stethoscope,
  pill: Pill,
  apple: Apple,
  salad: Salad,
  wine: Wine,
  beer: Beer,
  'cup-soda': CupSoda,
  pizza: Pizza,
  'ice-cream-cone': IceCreamCone,
  cake: Cake,
  popcorn: Popcorn,
  cigarette: Cigarette,
  wifi: Wifi,
  globe: Globe,
  phone: Phone,
  tv: Tv,
  monitor: Monitor,
  printer: Printer,
  wrench: Wrench,
  hammer: Hammer,
  lightbulb: Lightbulb,
  droplets: Droplets,
  flame: Flame,
  snowflake: Snowflake,
  umbrella: Umbrella,
  'cloud-rain': CloudRain,
  'tree-pine': TreePine,
  'flower-2': Flower2,
}

interface CategoryIconProps {
  name: string
  color?: string
  size?: number
  className?: string
}

export function CategoryIcon({
  name,
  color,
  size = 20,
  className,
}: CategoryIconProps) {
  const IconComponent = ICON_MAP[name] ?? Circle
  return (
    <IconComponent
      className={className}
      size={size}
      style={color ? { color } : undefined}
    />
  )
}
