// This file will be auto-generated by `supabase gen types typescript`
// For now, define manually based on the architecture document

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          currency: string
          theme: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          currency?: string
          theme?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          currency?: string
          theme?: string
          updated_at?: string
        }
        Relationships: []
      }
      categories: {
        Row: {
          id: string
          user_id: string
          name: string
          icon: string
          color: string
          sort_order: number
          is_archived: boolean
          is_default: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          icon?: string
          color?: string
          sort_order?: number
          is_archived?: boolean
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          icon?: string
          color?: string
          sort_order?: number
          is_archived?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          id: string
          user_id: string
          category_id: string | null
          type: 'expense' | 'income'
          amount: number
          date: string
          note: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          category_id?: string | null
          type?: 'expense' | 'income'
          amount: number
          date?: string
          note?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          category_id?: string | null
          type?: 'expense' | 'income'
          amount?: number
          date?: string
          note?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'transactions_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
        ]
      }
      budgets: {
        Row: {
          id: string
          user_id: string
          category_id: string
          amount: number
          month: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          category_id: string
          amount: number
          month?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          month?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'budgets_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_monthly_summary: {
        Args: { p_month: string }
        Returns: {
          category_id: string
          category_name: string
          category_icon: string
          category_color: string
          total_spent: number
          budget_amount: number
        }[]
      }
    }
    Enums: {
      transaction_type: 'expense' | 'income'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
